import pygame
import copy
import numpy as np


def visualize_policy(env, agent, fps: int = 10):
    """
    Launches an interactive Pygame window to visualize
    the agent's learned policy.

    The visualizer runs a single episode using a greedy
    policy (epsilon=0).
    It supports real-time telemetry, path history,
    and manual time-travel
    debugging via keyboard inputs.

    Keyboard Controls:
        [SPACE]: Toggle pause/play.
        [RIGHT ARROW]: Advance one step while paused.
        [LEFT ARROW]: Step back to the previous state (Undo).
        [R]: Reset the current episode and clear history.

    :param env: The environment instance to visualize.
    :param agent: The trained agent containing the Q-table.
    :param fps: Target frames per second for the simulation speed.
    """
    pygame.init()

    # --- Configuration ---
    CELL_SIZE = 60
    MARGIN = 4
    SIDEBAR_WIDTH = 250
    GRID_PX = env.grid_size * CELL_SIZE
    WIDTH = GRID_PX + SIDEBAR_WIDTH
    HEIGHT = GRID_PX

    # Colors
    BG_DARK = (18, 18, 18)
    BG_SIDEBAR = (30, 30, 35)
    TILE_EMPTY = (45, 45, 50)
    ACCENT_BLUE = (0, 150, 255)
    ACCENT_GREEN = (0, 230, 118)
    ACCENT_GOLD = (255, 215, 0)
    ACCENT_RED = (255, 61, 0)
    TEXT_MAIN = (240, 240, 240)
    TEXT_DIM = (160, 160, 160)

    ACTION_NAMES = {0: "NORTH ↑", 1: "SOUTH ↓", 2: "WEST ←",
                    3: "EAST →", 4: "CLEANING ⚡"}

    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("Smart Vacuum | Time-Travel Debugger")
    clock = pygame.time.Clock()

    font_main = pygame.font.SysFont("Inter, Segoe UI, Roboto", 24,
                                    bold=True)
    font_sub = pygame.font.SysFont("Inter, Segoe UI, Roboto", 16)

    # --- Snapshot Logic ---
    def get_snapshot():
        """
        Captures a deep copy of the current environment and simulation state.

        This memento pattern allows the visualizer to 'step back' in time by
        storing all mutable variables that define the current frame.

        :return: A dictionary containing the agent's position,
                dirt grid layout,
                battery level, current score, step count,
                and the encoded state ID.
        """
        return {
            'agent_pos': copy.deepcopy(env.agent_pos),
            'dirt_grid': copy.deepcopy(env.dirt_grid),
            'battery': env.battery,
            'total_points': total_points,
            'steps': steps,
            'current_action': current_action,
            'state_id': state  # the encoded integer state
        }

    def restore_snapshot(snap):
        """
        Restores the environment and visualizer variables to a previous state.

        :param snap: A snapshot dictionary previously
                    generated by get_snapshot().

        Directly modifies the environment's internal attributes and the
        visualizer's nonlocal tracking variables to effectively
        'rewind' the simulation.
        """
        nonlocal total_points, steps, current_action, state
        env.agent_pos = snap['agent_pos']
        env.dirt_grid = snap['dirt_grid']
        env.battery = snap['battery']
        total_points = snap['total_points']
        steps = snap['steps']
        current_action = snap['current_action']
        state = snap['state_id']

    # --- Simulation State ---
    state = env.reset()
    running = True
    paused = True  # Start paused to allow manual exploration
    step_once = False

    total_points = 0
    steps = 0
    current_action = -1
    history_stack = []  # The 'Undo' buffer
    MAX_HISTORY = 100

    def draw_sidebar(info, paused):
        """
        Renders the telemetry dashboard on the right side of the screen.

        Displays real-time data including:
        - Simulation status (Live vs. Paused)
        - The current action being executed by the agent
        - Total points (dynamic color: Green for positive, Red for negative)
        - Battery level (rendered as a dynamic progress bar)
        - Keyboard shortcut legend for user interaction

        :param info: Environment info dictionary containing 'battery'
                    and 'remaining_dirt'.
        :param paused: Current pause state of the simulation.
        """
        pygame.draw.rect(screen, BG_SIDEBAR,
                         (GRID_PX, 0, SIDEBAR_WIDTH, HEIGHT))
        pygame.draw.line(screen, (60, 60, 60), (GRID_PX, 0),
                         (GRID_PX, HEIGHT), 2)

        y = 30
        screen.blit(font_main.render("SIMULATION",
                                     True, TEXT_MAIN),
                                (GRID_PX + 20, y))

        status_color = ACCENT_RED if paused else ACCENT_GREEN
        screen.blit(font_sub.render("PAUSED" if paused else "LIVE",
                                    True, status_color),
                                (GRID_PX + 20, y + 30))

        y += 80
        screen.blit(font_sub.render("CURRENT ACTION",
                                    True, TEXT_DIM),
                                    (GRID_PX + 20, y))
        act_color = ACCENT_GOLD if current_action == 4 else ACCENT_BLUE
        screen.blit(font_main.render(ACTION_NAMES.get
        (current_action, "IDLE"), True, act_color),
    (GRID_PX + 20, y + 25))

        # --- Enhanced Points Highlight ---
        y += 90
        # Determine color based on positive/negative score
        points_color = ACCENT_GREEN if total_points >= 0 else ACCENT_RED
        score_label = font_sub.render("TOTAL POINTS", True,
                                      TEXT_DIM)
        score_val = font_main.render(f"{int(total_points)}",
                                     True, points_color)
        screen.blit(score_label, (GRID_PX + 20, y))
        screen.blit(score_val, (GRID_PX + 20, y + 25))

        # --- Battery Level Bar ---
        y += 80
        batt_pct = max(0.0, min(1.0, info['battery'] / env.max_battery))
        # Color transition: Green if >30%, otherwise Red
        bar_color = ACCENT_GREEN if batt_pct > 0.3 else ACCENT_RED

        batt_label = font_sub.render(f"BATTERY: {info['battery']:.1f}%",
                                     True, TEXT_DIM)
        screen.blit(batt_label, (GRID_PX + 20, y))

        # Draw background bar (container)
        bar_width = SIDEBAR_WIDTH - 40
        bar_height = 12
        bar_rect = pygame.Rect(GRID_PX + 20, y + 25, bar_width, bar_height)
        pygame.draw.rect(screen, (50, 50, 55), bar_rect,
                         border_radius=6)

        # Draw fill bar
        if batt_pct > 0:
            fill_width = int(bar_width * batt_pct)
            fill_rect = pygame.Rect(GRID_PX + 20, y + 25, fill_width,
                                    bar_height)
            pygame.draw.rect(screen, bar_color, fill_rect, border_radius=6)

        # Hotkeys (Moved further down)
        y = HEIGHT - 110
        hotkeys = [
            ("[SPACE] Play/Pause", TEXT_MAIN),
            ("[→] Step Forward", ACCENT_GREEN),
            ("[←] Step Back (Undo)", ACCENT_RED),
            ("[R] Restart", TEXT_DIM)
        ]
        for txt, color in hotkeys:
            screen.blit(font_sub.render(txt, True, color),
                        (GRID_PX + 20, y))
            y += 20

    def draw_grid():
        """
        Renders the vacuum environment grid and all entities within it.

        This function handles the drawing of:
        - Tile backgrounds with rounded corners.
        - The Base Station (Blue) and Dirt Orbs (Gold).
        - The Agent (Green) with a center indicator.
        - Special effects like the 'Cleaning Pulse' (Gold ring)
        when action 4 is active.
        """
        for y_idx in range(env.grid_size):
            for x_idx in range(env.grid_size):
                rect = pygame.Rect(x_idx * CELL_SIZE + MARGIN,
                                   y_idx * CELL_SIZE + MARGIN,
                                   CELL_SIZE - MARGIN * 2,
                                   CELL_SIZE - MARGIN * 2)
                pygame.draw.rect(screen, TILE_EMPTY, rect, border_radius=6)
                if (x_idx, y_idx) == env.base_pos:
                    pygame.draw.rect(screen, ACCENT_BLUE, rect,
                                     border_radius=6)
                if env.dirt_grid[y_idx, x_idx] == 1:
                    pygame.draw.circle(screen, ACCENT_GOLD,
                                       rect.center, 8)

        # Agent
        ax, ay = env.agent_pos
        center = (ax * CELL_SIZE + CELL_SIZE // 2, ay * CELL_SIZE +
                  CELL_SIZE // 2)
        if current_action == 4:
            pygame.draw.circle(screen, ACCENT_GOLD, center, CELL_SIZE // 2,
                               2)
        pygame.draw.circle(screen, ACCENT_GREEN, center, CELL_SIZE // 3)
        pygame.draw.circle(screen, (255, 255, 255), center, 5)

    # --- Main Loop ---
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT: running = False

            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_SPACE:
                    paused = not paused
                elif event.key == pygame.K_RIGHT:
                    step_once = True
                elif event.key == pygame.K_LEFT:
                    if history_stack:
                        restore_snapshot(history_stack.pop())
                elif event.key == pygame.K_r:
                    state = env.reset()
                    total_points, steps, current_action, history_stack = (
                        0, 0, -1, [])

        if not paused or step_once:
            # Save state before it changes
            history_stack.append(get_snapshot())
            if len(history_stack) > MAX_HISTORY: history_stack.pop(0)

            action = agent.select_action(state, epsilon=0.0)
            current_action = action

            next_state, reward, done, info = env.step(action)
            state = next_state
            total_points += reward
            steps += 1
            step_once = False

            if done:
                paused = True  # Pause on death/completion to let
                # user "rewind"

        # Render
        screen.fill(BG_DARK)
        draw_grid()
        current_info = {'battery': env.battery,
                        'remaining_dirt': np.sum(env.dirt_grid)}
        draw_sidebar(current_info, paused)

        pygame.display.flip()
        clock.tick(fps)

    pygame.quit()
